[project]
name = "shangan"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "duckdb>=1.3.0",
    "mito-ai>=0.1.21",
    "mitosheet>=0.2.21",
    "pandas>=2.2.3",
    "streamlit>=1.45.1",
    "xlrd>=2.0.1",
]
